// build.rs — re-run the build when the WIT interface changes.
//
// Guest bindings are generated by the `wit_bindgen::generate!` macro in
// src/component.rs, which expands at compile time rather than here. This hook
// exists so that editing the WIT actually triggers a rebuild of the crate.
fn main() {
    println!("cargo:rerun-if-changed=wit/gossip-protocol.wit");
}
