//! [`GossipNode`] — a single gossip node backed by a wasmtime component instance.
//!
//! Each node is an independent component instance with its own isolated linear
//! memory and global state, mirroring the real deployment model where each
//! validator process runs one instance.
//!
//! ## Component Model host bindings
//!
//! Host-side bindings are generated by [`wasmtime::component::bindgen!`] from
//! the same `wit/gossip-protocol.wit` the guest is generated from, so the host
//! and guest cannot drift: a signature change breaks this file at compile time.
//!
//! Note what is absent compared to the legacy core-module harness this
//! replaced: there is no allocator plumbing, no linear-memory reads/writes, and
//! no 12-byte out-slot decoding. The Component Model passes `list<u8>`,
//! `string`, `option`, and `result` natively, so those ~450 lines of manual
//! marshaling (and the whole of `abi.rs`) are gone.
//!
//! Each call site reaches through `self.bindings` and `self.store` as separate
//! fields rather than via a helper method, so the borrow checker can see the
//! two borrows are disjoint.

use anyhow::{Context, Result};
use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Engine, Store};
use wasmtime_wasi::p2::add_to_linker_sync;
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView};

wasmtime::component::bindgen!({
    world: "gossip-world",
    path: "../witan/wit",
});

use exports::witan::gossip::gossip_protocol::GossipError;

// ── Store context ─────────────────────────────────────────────────────────────

/// Per-instance host state: the WASI context and its resource table.
struct Ctx {
    table: ResourceTable,
    wasi: WasiCtx,
}

impl WasiView for Ctx {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.wasi,
            table: &mut self.table,
        }
    }
}

/// Render a guest-returned `gossip-error` for test output.
///
/// The variant is preserved structurally by the Component Model, so unlike the
/// legacy ABI there is no JSON error string to parse back out.
fn err(context: &str, e: GossipError) -> anyhow::Error {
    anyhow::anyhow!("{context}: {e:?}")
}

// ── GossipNode ────────────────────────────────────────────────────────────────

/// A single gossip node backed by a wasmtime component instance.
pub struct GossipNode {
    /// Human-readable address used as the peer identifier (e.g. `"node-a"`).
    pub addr: String,

    store: Store<Ctx>,
    bindings: GossipWorld,
}

impl GossipNode {
    /// Instantiate a new gossip node from a compiled component.
    pub fn new(addr: impl Into<String>, component_bytes: &[u8], engine: &Engine) -> Result<Self> {
        let addr = addr.into();

        let component = Component::from_binary(engine, component_bytes)
            .map_err(|e| anyhow::anyhow!("{addr}: loading component: {e}"))?;

        let mut linker = Linker::new(engine);
        add_to_linker_sync(&mut linker)
            .map_err(|e| anyhow::anyhow!("{addr}: linking WASI: {e}"))?;

        let ctx = Ctx {
            table: ResourceTable::new(),
            wasi: WasiCtxBuilder::new().inherit_stdio().build(),
        };
        let mut store = Store::new(engine, ctx);

        let bindings = GossipWorld::instantiate(&mut store, &component, &linker)
            .map_err(|e| anyhow::anyhow!("{addr}: instantiating component: {e}"))?;

        Ok(Self {
            addr,
            store,
            bindings,
        })
    }

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    /// Initialize the node with a JSON configuration.
    pub fn init(&mut self, config_json: &str) -> Result<()> {
        self.bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_init(&mut self.store, config_json)?
            .map_err(|e| err("gossip_init", e))
    }

    /// Get the component's version string.
    pub fn get_version(&mut self) -> Result<String> {
        Ok(self
            .bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_get_version(&mut self.store)?)
    }

    /// Get the current Unix timestamp in milliseconds, as seen by the guest.
    #[allow(dead_code)]
    pub fn now_ms(&mut self) -> Result<u64> {
        Ok(self
            .bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_now_ms(&mut self.store)?)
    }

    // ── Identity ──────────────────────────────────────────────────────────────

    /// Get this node's public identity as parsed JSON.
    pub fn get_node_identity(&mut self) -> Result<serde_json::Value> {
        let json = self
            .bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_get_node_identity(&mut self.store)?
            .map_err(|e| err("gossip_get_node_identity", e))?;
        serde_json::from_str(&json).context("parsing node identity JSON")
    }

    /// Rotate this node's identity keys, returning the new node ID.
    #[allow(dead_code)]
    pub fn rotate_keys(&mut self) -> Result<String> {
        self.bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_rotate_keys(&mut self.store)?
            .map_err(|e| err("gossip_rotate_keys", e))
    }

    // ── Peers and handshake ───────────────────────────────────────────────────

    /// Initiate a handshake with a peer, returning the probe bytes to send.
    pub fn connect_peer(&mut self, peer_addr: &str) -> Result<Vec<u8>> {
        self.bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_connect_peer(&mut self.store, peer_addr)?
            .map_err(|e| err("gossip_connect_peer", e))
    }

    /// Process incoming handshake bytes, returning any response to send back.
    pub fn process_handshake_bytes(
        &mut self,
        peer_addr: &str,
        bytes: &[u8],
    ) -> Result<Option<Vec<u8>>> {
        self.bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_process_handshake_bytes(&mut self.store, peer_addr, bytes)?
            .map_err(|e| err("gossip_process_handshake_bytes", e))
    }

    /// Disconnect from a peer.
    pub fn disconnect_peer(&mut self, peer_addr: &str) -> Result<()> {
        self.bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_disconnect_peer(&mut self.store, peer_addr)?
            .map_err(|e| err("gossip_disconnect_peer", e))
    }

    /// Get the connected peer list as parsed JSON objects.
    pub fn get_peers(&mut self) -> Result<Vec<serde_json::Value>> {
        let json = self
            .bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_get_peers(&mut self.store)?
            .map_err(|e| err("gossip_get_peers", e))?;
        serde_json::from_str(&json).context("parsing peers JSON")
    }

    /// Get session info for a peer as parsed JSON.
    #[allow(dead_code)]
    pub fn get_session(&mut self, peer_addr: &str) -> Result<serde_json::Value> {
        let json = self
            .bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_get_session(&mut self.store, peer_addr)?
            .map_err(|e| err("gossip_get_session", e))?;
        serde_json::from_str(&json).context("parsing session JSON")
    }

    // ── Messaging ─────────────────────────────────────────────────────────────

    /// Publish a message, returning its 32-byte message ID.
    pub fn publish(&mut self, payload_type: u8, payload: &[u8]) -> Result<[u8; 32]> {
        let id = self
            .bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_publish(&mut self.store, payload_type, payload)?
            .map_err(|e| err("gossip_publish", e))?;
        id.as_slice()
            .try_into()
            .with_context(|| format!("expected a 32-byte message ID, got {} bytes", id.len()))
    }

    /// Encode a signed envelope for wire transmission.
    pub fn encode_envelope(&mut self, payload_type: u8, payload: &[u8]) -> Result<Vec<u8>> {
        self.bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_encode_envelope(&mut self.store, payload_type, payload)?
            .map_err(|e| err("gossip_encode_envelope", e))
    }

    /// Decode an envelope to parsed JSON.
    #[allow(dead_code)]
    pub fn decode_envelope(&mut self, bytes: &[u8]) -> Result<serde_json::Value> {
        let json = self
            .bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_decode_envelope(&mut self.store, bytes)?
            .map_err(|e| err("gossip_decode_envelope", e))?;
        serde_json::from_str(&json).context("parsing envelope JSON")
    }

    /// Verify a received envelope.
    pub fn verify_envelope(&mut self, bytes: &[u8]) -> Result<bool> {
        self.bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_verify_envelope(&mut self.store, bytes)?
            .map_err(|e| err("gossip_verify_envelope", e))
    }

    /// Verify a standalone ML-DSA-65 signature.
    #[allow(dead_code)]
    pub fn verify_signature(
        &mut self,
        public_key: &[u8],
        message: &[u8],
        signature: &[u8],
        context: &[u8],
    ) -> Result<bool> {
        self.bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_verify_signature(
                &mut self.store,
                public_key,
                message,
                signature,
                context,
            )?
            .map_err(|e| err("gossip_verify_signature", e))
    }

    // ── Stats ─────────────────────────────────────────────────────────────────

    /// Get runtime statistics as parsed JSON.
    pub fn get_stats(&mut self) -> Result<serde_json::Value> {
        let json = self
            .bindings
            .witan_gossip_gossip_protocol()
            .call_gossip_get_stats(&mut self.store)?
            .map_err(|e| err("gossip_get_stats", e))?;
        serde_json::from_str(&json).context("parsing stats JSON")
    }
}
